In [1]:
import pandas as pd
import numpy as py
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sn

In [3]:
df = pd.read_csv("/kaggle/input/datasets/kapoorprakhar/ibm-hr-analytics-employee-attrition-enhanced/IBM_HR_Attrition_Enhanced.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
 35  AgeGroup                  1470 non-null   object
 36  TenureGroup               1470 non-null   object
 37  MonthlyIncomeBracket      1470 non-null   object
 38  OverallSatisfactionIndex  1470 non-null   float64
dtypes: float64(1), int64(26), object(12)
memory usage: 448.0+ KB

In [5]:
df.shape

(1470, 39)

In [6]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,OverallSatisfactionIndex
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129,2.730952
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136,0.505815
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000,2.500000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000,2.750000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000,3.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000,4.000000

In [7]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
AgeGroup                    0
TenureGroup                 0
MonthlyIncomeBracket        0
OverallSatisfactionIndex    0
dtype: int64

In [8]:
pd.set_option('display.max_columns', None)

# Now df.head() will display every column

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,MonthlyIncomeBracket,OverallSatisfactionIndex
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5,35-44,Established (6-10 yrs),High,2.00
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7,45-54,Established (6-10 yrs),High,3.00
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0,35-44,New (0-2 yrs),Low,3.00
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0,25-34,Established (6-10 yrs),Low,3.25
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2,25-34,New (0-2 yrs),Medium,2.50

In [11]:
Categoricalcolumns=['Attrition','BusinessTravel','Department','EducationField','Gender','JobRole',
                                  'MaritalStatus','OverTime','MonthlyIncomeBracket']
df1 = pd.get_dummies(df,columns=Categoricalcolumns,  drop_first=True, dtype=int)

In [12]:
pd.set_option('display.max_columns', None)

# Now df.head() will display every column

df1.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,OverallSatisfactionIndex,Attrition_Yes,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Research & Development,Department_Sales,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,MonthlyIncomeBracket_Low,MonthlyIncomeBracket_Medium,MonthlyIncomeBracket_Very High
0,41,1102,1,2,1,1,2,94,3,2,4,5993,19479,8,Y,11,3,1,80,0,8,0,1,6,4,0,5,35-44,Established (6-10 yrs),2.00,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0
1,49,279,8,1,1,2,3,61,2,2,2,5130,24907,1,Y,23,4,4,80,1,10,3,3,10,7,1,7,45-54,Established (6-10 yrs),3.00,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0
2,37,1373,2,2,1,4,4,92,2,1,3,2090,2396,6,Y,15,3,2,80,0,7,3,3,0,0,0,0,35-44,New (0-2 yrs),3.00,1,0,1,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,1,1,0,0
3,33,1392,3,4,1,5,4,56,3,1,3,2909,23159,1,Y,11,3,3,80,0,8,3,3,8,7,3,0,25-34,Established (6-10 yrs),3.25,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0
4,27,591,2,1,1,7,1,40,3,1,2,3468,16632,9,Y,12,3,4,80,1,6,3,3,2,2,2,2,25-34,New (0-2 yrs),2.50,0,0,1,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0

In [13]:
def calculate_midpoint(age_range):
    try:
        # Split the string by the hyphen
        low, high = map(float, age_range.split("-"))
        # Return the average
        return (low + high) / 2
    except:
        # Handle missing or broken values safely
        return None


# 3. Apply the function to the column
df1["AgeGroup"]=df1["AgeGroup"].apply(calculate_midpoint)

In [15]:

import re

def range_average(value):
    match = re.search(r'(\d+)\s*-\s*(\d+)', str(value))
    
    if match:
        lower = int(match.group(1))
        upper = int(match.group(2))
        return (lower + upper) / 2
    
    return value

df1['TenureGroup'] = df1['TenureGroup'].apply(range_average)

In [16]:
df1.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,OverallSatisfactionIndex,Attrition_Yes,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Research & Development,Department_Sales,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,MonthlyIncomeBracket_Low,MonthlyIncomeBracket_Medium,MonthlyIncomeBracket_Very High
0,41,1102,1,2,1,1,2,94,3,2,4,5993,19479,8,Y,11,3,1,80,0,8,0,1,6,4,0,5,39.5,8.0,2.00,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0
1,49,279,8,1,1,2,3,61,2,2,2,5130,24907,1,Y,23,4,4,80,1,10,3,3,10,7,1,7,49.5,8.0,3.00,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0
2,37,1373,2,2,1,4,4,92,2,1,3,2090,2396,6,Y,15,3,2,80,0,7,3,3,0,0,0,0,39.5,1.0,3.00,1,0,1,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,1,1,0,0
3,33,1392,3,4,1,5,4,56,3,1,3,2909,23159,1,Y,11,3,3,80,0,8,3,3,8,7,3,0,29.5,8.0,3.25,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0
4,27,591,2,1,1,7,1,40,3,1,2,3468,16632,9,Y,12,3,4,80,1,6,3,3,2,2,2,2,29.5,1.0,2.50,0,0,1,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0

In [17]:
df1['Over18'].value_counts()

Over18
Y    1470
Name: count, dtype: int64

In [19]:
df1['Over18'] = df1['Over18'].replace('Y', '1')
df1['Over18']=df1['Over18'].astype(int)

In [20]:
df1['Over18'].value_counts()

Over18
1    1470
Name: count, dtype: int64

In [21]:
from sklearn.preprocessing import StandardScaler
scale_cols = ['MonthlyIncome', 'MonthlyRate','StandardHours','DailyRate','HourlyRate']

# 3. Initialize and apply the StandardScaler
scaler = StandardScaler()
df1[scale_cols] = scaler.fit_transform(df1[scale_cols])

In [22]:
df1.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,OverallSatisfactionIndex,Attrition_Yes,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Research & Development,Department_Sales,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,MonthlyIncomeBracket_Low,MonthlyIncomeBracket_Medium,MonthlyIncomeBracket_Very High
0,41,0.742527,1,2,1,1,2,1.383138,3,2,4,-0.108350,0.726020,8,1,11,3,1,0.0,0,8,0,1,6,4,0,5,39.5,8.0,2.00,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0
1,49,-1.297775,8,1,1,2,3,-0.240677,2,2,2,-0.291719,1.488876,1,1,23,4,4,0.0,1,10,3,3,10,7,1,7,49.5,8.0,3.00,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0
2,37,1.414363,2,2,1,4,4,1.284725,2,1,3,-0.937654,-1.674841,6,1,15,3,2,0.0,0,7,3,3,0,0,0,0,39.5,1.0,3.00,1,0,1,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,1,1,0,0
3,33,1.461466,3,4,1,5,4,-0.486709,3,1,3,-0.763634,1.243211,1,1,11,3,3,0.0,0,8,3,3,8,7,3,0,29.5,8.0,3.25,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0
4,27,-0.524295,2,1,1,7,1,-1.274014,3,1,2,-0.644858,0.325900,9,1,12,3,4,0.0,1,6,3,3,2,2,2,2,29.5,1.0,2.50,0,0,1,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0

In [23]:
df1['Attrition_Yes']=df1['Attrition_Yes'].astype(int)

In [24]:
Y=df1['Attrition_Yes']
X=df1.drop('Attrition_Yes',axis=1)

In [25]:
# Creating an instance from 'LogisticRegression_with_p_values()' class.
from sklearn.linear_model import LogisticRegression
import numpy as np
import statsmodels.api as sm
from sklearn import metrics  
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn import linear_model
import scipy.stats as stat

  

class LogisticRegression_with_p_values:
    """
    Wrapper Class for Logistic Regression which has the usual sklearn instance 
    in an attribute self.model, and pvalues, z scores and estimated 
    errors for each coefficient in 
    
    self.z_scores
    self.p_values
    self.sigma_estimates
    
    as well as the negative hessian of the log Likelihood (Fisher information)
    
    self.F_ij
    """
    
    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.model.fit(X,y)
        
        #### Get p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X) ## Fisher Information Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Information Matrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates # z-score for each model coefficient
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### two tailed test for p-values
        
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

# following function is taken as adapted in a lecture note of 365 datascience
# will be imported to src file

# Since we are using an object oriented language such as Python, we can simply define our own 
# LinearRegression class (the same one from sklearn)
# By typing the code below we will ovewrite a part of the class with one that includes p-values
# Here's the full source code of the ORIGINAL class: https://github.com/scikit-learn/scikit-learn/blob/7b136e9/sklearn/linear_model/base.py#L362

In [27]:
# Creating an instance from 'LogisticRegression_with_p_values()' class.
reg = LogisticRegression_with_p_values()

In [28]:
print(X.select_dtypes(include='object').columns)

Index(['TenureGroup'], dtype='object')

In [29]:
df1['TenureGroup'].value_counts()

TenureGroup
8.0                  448
4.0                  434
1.0                  342
Veteran (10+ yrs)    246
Name: count, dtype: int64

In [31]:
def range_average1(value):
    match = re.search(r'(\d+)\s*', str(value))
    
    if match:
        lower = int(match.group(1))
        
        return lower
    
    return value

df1['TenureGroup'] = df1['TenureGroup'].apply(range_average1)

In [32]:
df1['TenureGroup']=df1['TenureGroup'].astype(int)

In [33]:
df1['TenureGroup'].value_counts()

TenureGroup
8     448
4     434
1     342
10    246
Name: count, dtype: int64

In [34]:
print(df1.dtypes)

Age                                    int64
DailyRate                            float64
DistanceFromHome                       int64
Education                              int64
EmployeeCount                          int64
EmployeeNumber                         int64
EnvironmentSatisfaction                int64
HourlyRate                           float64
JobInvolvement                         int64
JobLevel                               int64
JobSatisfaction                        int64
MonthlyIncome                        float64
MonthlyRate                          float64
NumCompaniesWorked                     int64
Over18                                 int64
PercentSalaryHike                      int64
PerformanceRating                      int64
RelationshipSatisfaction               int64
StandardHours                        float64
StockOptionLevel                       int64
TotalWorkingYears                      int64
TrainingTimesLastYear                  int64
WorkLifeBalance                        int64
YearsAtCompany                         int64
YearsInCurrentRole                     int64
YearsSinceLastPromotion                int64
YearsWithCurrManager                   int64
AgeGroup                             float64
TenureGroup                            int64
OverallSatisfactionIndex             float64
Attrition_Yes                          int64
BusinessTravel_Travel_Frequently       int64
BusinessTravel_Travel_Rarely           int64
Department_Research & Development      int64
Department_Sales                       int64
EducationField_Life Sciences           int64
EducationField_Marketing               int64
EducationField_Medical                 int64
EducationField_Other                   int64
EducationField_Technical Degree        int64
Gender_Male                            int64
JobRole_Human Resources                int64
JobRole_Laboratory Technician          int64
JobRole_Manager                        int64
JobRole_Manufacturing Director         int64
JobRole_Research Director              int64
JobRole_Research Scientist             int64
JobRole_Sales Executive                int64
JobRole_Sales Representative           int64
MaritalStatus_Married                  int64
MaritalStatus_Single                   int64
OverTime_Yes                           int64
MonthlyIncomeBracket_Low               int64
MonthlyIncomeBracket_Medium            int64
MonthlyIncomeBracket_Very High         int64
dtype: object

In [36]:
df1['AgeGroup'] = df1['AgeGroup'].fillna(
    df1['AgeGroup'].mode()[0]
)

In [38]:
Y=df1['Attrition_Yes']
X=df1.drop('Attrition_Yes',axis=1)

In [39]:
print(X.isna().sum()[X.isna().sum() > 0])

Series([], dtype: int64)

In [40]:
corr = X.corr().abs()

high_corr = corr.where(
    np.triu(np.ones(corr.shape), k=1).astype(bool)
).stack()

print(high_corr[high_corr > 0.85].sort_values(ascending=False))

JobLevel                           MonthlyIncome                     0.950300
Department_Research & Development  Department_Sales                  0.906818
MonthlyIncome                      MonthlyIncomeBracket_Very High    0.860167
dtype: float64

In [42]:
col1=['JobLevel','Department_Sales','MonthlyIncomeBracket_Very High','TenureGroup','PerformanceRating','TotalWorkingYears','YearsWithCurrManager','BusinessTravel_Travel_Rarely']
X=X.drop(col1,axis=1, errors='ignore')

In [43]:
X.columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'AgeGroup',
       'OverallSatisfactionIndex', 'BusinessTravel_Travel_Frequently',
       'Department_Research & Development', 'EducationField_Life Sciences',
       'EducationField_Marketing', 'EducationField_Medical',
       'EducationField_Other', 'EducationField_Technical Degree',
       'Gender_Male', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'OverTime_Yes', 'MonthlyIncomeBracket_Low',
       'MonthlyIncomeBracket_Medium'],
      dtype='object')

In [44]:
corr = X.corr().abs()

high_corr = corr.where(
    np.triu(np.ones(corr.shape), k=1).astype(bool)
).stack()

print(high_corr[high_corr > 0.75].sort_values(ascending=False))

YearsAtCompany  YearsInCurrentRole    0.758754
dtype: float64

In [45]:
from sklearn.model_selection import train_test_split

# Split into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [46]:
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=10000)

# 3. Train the model using the training data
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [47]:
y_pred = model.predict(X_test)

# 5. Calculate and print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 89.12%

In [ ]:
attrition_counts = df["Attrition"].value_counts()

In [ ]:
plt.figure(figsize=(6,4))
plt.bar(attrition_counts.index, attrition_counts.values)


plt.title("Employee Attrition Distribution")
plt.xlabel("Attrition")
plt.ylabel("Number of Employees")


plt.show()

In [ ]:
plt.figure(figsize=(8,5))
plt.hist(df["Age"], bins=10)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Employees")

plt.show()

In [ ]:
yes_income = df[df["Attrition"] == "Yes"]["MonthlyIncome"]
no_income = df[df["Attrition"] == "No"]["MonthlyIncome"]

plt.figure(figsize=(7,5))
plt.boxplot([yes_income, no_income], tick_labels=["Yes", "No"])

plt.title("Monthly Income by Attrition")
plt.xlabel("Attrition")
plt.ylabel("Monthly Income")

plt.show()

In [ ]:
department_attrition = pd.crosstab(df["Department"], df["Attrition"])

department_attrition.plot(kind="bar", figsize=(8,5))

plt.title("Attrition by Department")
plt.xlabel("Department")
plt.ylabel("Number of Employees")

plt.show()

In [ ]:
avg_income = df.groupby("JobRole")["MonthlyIncome"].mean()

plt.figure(figsize=(10,5))
plt.bar(avg_income.index, avg_income.values)

plt.xticks(rotation=45)
plt.title("Average Monthly Income by Job Role")
plt.xlabel("Job Role")
plt.ylabel("Average Monthly Income")

plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(7,5))
plt.scatter(df["Age"], df["MonthlyIncome"])

plt.title("Age vs Monthly Income")
plt.xlabel("Age")
plt.ylabel("Monthly Income")

plt.show()

In [ ]:
avg_satisfaction = df.groupby("Attrition")["OverallSatisfactionIndex"].mean()

plt.figure(figsize=(6,4))
plt.bar(avg_satisfaction.index, avg_satisfaction.values)

plt.title("Average Satisfaction by Attrition")
plt.xlabel("Attrition")
plt.ylabel("Average Satisfaction Index")

plt.show()

In [ ]:
overtime_attrition = pd.crosstab(df["OverTime"], df["Attrition"])

overtime_attrition.plot(kind="bar", figsize=(6,5))

plt.title("Overtime vs Attrition")
plt.xlabel("Overtime")
plt.ylabel("Number of Employees")

plt.show()

In [ ]:
numeric_df = df.select_dtypes(include="number")


corr = numeric_df.corr()

plt.figure(figsize=(12,10))
plt.imshow(corr, cmap="coolwarm", aspect="auto")
plt.colorbar()

plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)

plt.title("Correlation Heatmap")
plt.tight_layout()

plt.show()

In [ ]:
job_attrition = pd.crosstab(df["JobRole"], df["Attrition"])

job_attrition.plot(kind="bar", figsize=(10,6))

plt.title("Attrition by Job Role")
plt.xlabel("Job Role")
plt.ylabel("Number of Employees")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

In [ ]:
education = pd.crosstab(df["EducationField"], df["Attrition"])

education.plot(kind="bar", figsize=(9,5))

plt.title("Attrition by Education Field")
plt.xlabel("Education Field")
plt.ylabel("Employees")

plt.xticks(rotation=30)
plt.tight_layout()

plt.show()

In [ ]:
plt.figure(figsize=(7,5))

plt.hist(df["JobSatisfaction"], bins=4)

plt.title("Job Satisfaction Distribution")
plt.xlabel("Job Satisfaction")
plt.ylabel("Employees")

plt.show()

In [ ]:
plt.figure(figsize=(8,5))

plt.hist(df["YearsAtCompany"], bins=15)

plt.title("Years at Company")
plt.xlabel("Years")
plt.ylabel("Employees")

plt.show()

In [ ]:
plt.figure(figsize=(7,5))

plt.scatter(df["YearsAtCompany"], df["MonthlyIncome"])

plt.title("Years at Company vs Monthly Income")
plt.xlabel("Years at Company")
plt.ylabel("Monthly Income")

plt.show()

In [ ]:
plt.figure(figsize=(8,5))

plt.hist(df["DistanceFromHome"], bins=15)

plt.title("Distance From Home")
plt.xlabel("Distance")
plt.ylabel("Employees")

plt.show()

In [ ]:
overtime = df["OverTime"].value_counts()

plt.figure(figsize=(5,4))

plt.bar(overtime.index, overtime.values)

plt.title("Employees Working Overtime")
plt.xlabel("OverTime")
plt.ylabel("Count")

plt.show()

In [ ]:
ratings = df["PerformanceRating"].value_counts().sort_index()

plt.figure(figsize=(6,4))

plt.bar(ratings.index.astype(str), ratings.values)

plt.title("Performance Ratings")
plt.xlabel("Rating")
plt.ylabel("Employees")

plt.show()

In [ ]:
plt.figure(figsize=(8,5))

plt.hist(df["MonthlyIncome"], bins=20)

plt.title("Monthly Income Distribution")
plt.xlabel("Income")
plt.ylabel("Employees")

plt.show()

In [ ]:
income = df.groupby("Department")["MonthlyIncome"].mean()

plt.figure(figsize=(7,5))

plt.bar(income.index, income.values)

plt.title("Average Monthly Income by Department")
plt.xlabel("Department")
plt.ylabel("Average Income")

plt.show()

In [ ]:
years = df.groupby("Department")["YearsAtCompany"].mean()

plt.figure(figsize=(7,5))

plt.bar(years.index, years.values)

plt.title("Average Years at Company by Department")
plt.xlabel("Department")
plt.ylabel("Average Years")

plt.show()

In [ ]:
education = df["Education"].value_counts().sort_index()

plt.figure(figsize=(6,4))

plt.bar(education.index.astype(str), education.values)

plt.title("Education Levels")
plt.xlabel("Education Level")
plt.ylabel("Employees")

plt.show()

In [ ]:
departments = df["Department"].unique()
income_data = [df[df["Department"] == dept]["MonthlyIncome"] for dept in departments]

plt.figure(figsize=(8,5))

plt.boxplot(income_data, tick_labels=departments)

plt.title("Monthly Income by Department")
plt.xlabel("Department")
plt.ylabel("Monthly Income")

plt.show()

In [ ]:
attrition_rate = (
    df.groupby("Department")["Attrition"]
      .apply(lambda x: (x == "Yes").mean() * 100)
)

plt.figure(figsize=(7,5))

plt.bar(attrition_rate.index, attrition_rate.values)

plt.title("Attrition Rate by Department")
plt.xlabel("Department")
plt.ylabel("Attrition Rate (%)")

plt.show()

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    roc_curve,
    roc_auc_score
)

In [ ]:
df["Attrition"] = df["Attrition"].map({"No":0,"Yes":1})

In [ ]:
if "EmployeeNumber" in df.columns:
    df = df.drop("EmployeeNumber", axis=1)

In [ ]:
df = pd.get_dummies(df, drop_first=True)

In [ ]:
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
parameters = {
    "C":[0.001,0.01,0.1,1,10,100],
    "penalty":["l2"],
    "solver":["lbfgs"]
}

grid = GridSearchCV(
    LogisticRegression(max_iter=1000),
    parameters,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid.fit(X_train,y_train)

print("Best Parameters")
print(grid.best_params_)

print("\nBest Cross Validation Accuracy")
print(grid.best_score_)

In [ ]:
model = grid.best_estimator_

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_prob = model.predict_proba(X_test)[:,1]

In [ ]:
print("\nAccuracy")
print(accuracy_score(y_test,y_pred))

print("\nClassification Report")
print(classification_report(y_test,y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred))

In [ ]:
auc = roc_auc_score(y_test,y_prob)

print("\nROC AUC Score")
print(auc)

In [ ]:
ConfusionMatrixDisplay.from_predictions(y_test,y_pred)

plt.title("Confusion Matrix")
plt.show()

In [ ]:
fpr,tpr,thresholds = roc_curve(y_test,y_prob)

plt.figure(figsize=(6,5))
plt.plot(fpr,tpr,label=f"AUC = {auc:.3f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

plt.show()

In [ ]:
coefficients = pd.DataFrame({
    "Feature":X.columns,
    "Coefficient":model.coef_[0]
})

coefficients["Absolute"] = coefficients["Coefficient"].abs()

coefficients = coefficients.sort_values(
    by="Absolute",
    ascending=False
)

print("\nTop 20 Important Features")
print(coefficients.head(20))

In [ ]:
top20 = coefficients.head(20)

plt.figure(figsize=(10,7))
plt.barh(top20["Feature"],top20["Coefficient"])
plt.title("Top 20 Logistic Regression Coefficients")
plt.xlabel("Coefficient Value")
plt.gca().invert_yaxis()
plt.tight_layout()

plt.show()